permalink: pretty
exclude: [utils, examples]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections_dir: collections
collections:
  modules:
    output: true
    sort_by: title
    permalink: /:title/
  respawn:
    output: true
    sort_by: title
    permalink: /respawn/:title/
  halo-breakpoint:
    output: true
    sort_by: title
    permalink: /halo-breakpoint/:title/