permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
collections_dir: collections
collections:
  modules:
    output: true
    sort_by: title
  shadow-war:
    output: true
    sort_by: title
    permalink: /modules/shadow-war/:title/
  halo-firefight:
    output: true
    sort_by: title
    permalink: /modules/halo-firefight/:title/
  legions:
    output: true
    sort_by: title
    permalink: /modules/legions/:title/
  squadrons:
    output: true
    sort_by: title
    permalink: /modules/squadrons/:title/