permalink: pretty
exclude: [utils, examples]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections_dir: collections
collections:
  modules:
    output: true
    sort_by: title
    permalink: /:title/
  shadow-war:
    output: true
    sort_by: title
  halo-firefight:
    output: true
    sort_by: title
  legions:
    output: true
    sort_by: title
  squadrons:
    output: true
    sort_by: title
  guilds-and-glory:
    output: true
    sort_by: title
