permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "single"
collections:
  modules:
    output: true
    sort_by: title
  shadow-war:
    output: true
    sort_by: title
  halo-firefight:
    output: true
    sort_by: title
  legions:
    output: true
    sort_by: title
collections_dir: collections