permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
collections_dir: collections
collections:
  modules:
    output: true
    sort_by: title
    permalink: /:title/
  shadow-war:
    output: true
    sort_by: title
  halo-firefight:
    output: true
    sort_by: title
  legions:
    output: true
    sort_by: title
  squadrons:
    output: true
    sort_by: title